import { JobOrder, FilmStockItem, PublisherClient, NotificationItem } from "./types";

export const INITIAL_JOBS: JobOrder[] = [
  {
    id: "#ORD-009",
    bookTitle: "বিদ্যাকোষ-বাংলা ভাষার ব্যাকরণ ও নির্মিতি - অষ্টম শ্রেণি",
    publisherName: "Sagorica Publications",
    pressName: "Nova Lamination",
    pressOwnerName: "Md. Abdur Rahim",
    coversCount: 2000,
    laminationType: "Matte 30μm",
    dueDate: "Aug 10, 2026",
    orderDate: "Jul 20, 2026",
    status: "Awaiting Proof",
    estimatedFilmMeters: 1400,
    proofPhotoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcLiqouJrqFAiLNs5KclUB0rxj6KsoCM8ojeEjqps_Fg&s=10",
    proofNote: "Applied Matte finish sample run (2 test covers). Please verify edge pasting & color depth.",
    proofLogs: [
      {
        id: "log-1",
        timestamp: "2026-07-21 14:30",
        action: "uploaded",
        actor: "Md. Abdur Rahim (Nova Lamination)",
        role: "press_owner",
        note: "Uploaded sample proof photo for 2 test covers.",
        photoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcLiqouJrqFAiLNs5KclUB0rxj6KsoCM8ojeEjqps_Fg&s=10",
      },
    ],
    totalIntake: 2000,
    goodOutput: 1950,
    wasteCount: 50,
    yieldVerified: true,
    invoiceId: "INV-2026-009",
    amountBdt: 45000,
    invoiceDueDate: "2026-06-18",
    paymentStatus: "Overdue",
    daysOverdue: 33,
  },
  {
    id: "#ORD-008",
    bookTitle: "A self-learning For Writing Test 1st and 2nd Paper",
    publisherName: "Sagorica Publications",
    pressName: "Nova Lamination",
    pressOwnerName: "Md. Abdur Rahim",
    coversCount: 1500,
    laminationType: "Gloss 24μm",
    dueDate: "Aug 05, 2026",
    orderDate: "Jul 15, 2026",
    status: "In Production",
    estimatedFilmMeters: 1050,
    proofPhotoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcLiqouJrqFAiLNs5KclUB0rxj6KsoCM8ojeEjqps_Fg&s=10",
    proofNote: "Gloss 24μm sample approved by publisher.",
    proofLogs: [
      {
        id: "log-2",
        timestamp: "2026-07-16 10:15",
        action: "uploaded",
        actor: "Md. Abdur Rahim",
        role: "press_owner",
        note: "Uploaded Gloss test sample.",
      },
      {
        id: "log-3",
        timestamp: "2026-07-16 11:45",
        action: "approved",
        actor: "Shahin Ahmed Mithu",
        role: "publisher",
        note: "Approved for full production run.",
      },
    ],
    totalIntake: 1500,
    goodOutput: 1470,
    wasteCount: 30,
    yieldVerified: true,
    invoiceId: "INV-2026-008",
    amountBdt: 31500,
    invoiceDueDate: "2026-08-16",
    paymentStatus: "Unpaid",
    daysOverdue: 0,
  },
];

export const INITIAL_STOCK: FilmStockItem[] = [
  {
    id: "stk-1",
    type: "Matte 30μm",
    availableMeters: 4500,
    rollWidthCm: 72,
    minThresholdMeters: 1000,
    lastRestocked: "2026-07-15",
  },
  {
    id: "stk-2",
    type: "Gloss 24μm",
    availableMeters: 800,
    rollWidthCm: 72,
    minThresholdMeters: 1500,
    lastRestocked: "2026-07-02",
  },
  {
    id: "stk-3",
    type: "Velvet Touch",
    availableMeters: 2200,
    rollWidthCm: 65,
    minThresholdMeters: 800,
    lastRestocked: "2026-07-10",
  },
  {
    id: "stk-4",
    type: "Thermal Matte",
    availableMeters: 3100,
    rollWidthCm: 70,
    minThresholdMeters: 1000,
    lastRestocked: "2026-07-12",
  },
];

export const INITIAL_PUBLISHERS: PublisherClient[] = [
  {
    id: "pub-1",
    name: "Sagorica Publications",
    contactPerson: "Shahin Ahmed Mithu",
    phone: "+880 1711-456789",
    email: "orders@sagorikabooks.bd",
    location: "Banglabazar, Dhaka",
    totalOrders: 14,
    outstandingBalanceBdt: 76500,
    oldestOverdueDays: 33,
    creditHoldStatus: true,
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: "notif-1",
    timestamp: "10 mins ago",
    title: "Proof Uploaded",
    message: "Nova Lamination uploaded a test proof.",
    type: "proof",
    unread: true,
    jobId: "#ORD-009",
  },
  {
    id: "notif-2",
    timestamp: "1 hour ago",
    title: "Low Stock Alert",
    message: "Gloss 24μm film stock (800m) is below minimum threshold (1500m).",
    type: "stock",
    unread: true,
  },
  {
    id: "notif-3",
    timestamp: " Yesterday",
    title: "Credit Hold Triggered",
    message: "Sagorica Publications account placed on automated credit hold (33 days overdue).",
    type: "credit",
    unread: false,
  },
];

